image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test
  - Build & Push

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint main.py

unittests:
  stage: Test
  allow_failure: true
  script:
  - python test.py

build-push-docker-image-job:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_URL
    - echo "Hello There !!"
#     - docker build -t $IMAGE_NAME .
#     - docker push $IMAGE_NAME