image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test
  - Build & Push

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint main.py

unittests:
  stage: Test
  allow_failure: true
  script:
  - python test.py

# build-push-docker-image-job:
#   image: docker:latest
#   services:
#     - docker:dind
#   before_script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   script:
#     - docker build -t $IMAGE_NAME .
#     - docker push $IMAGE_NAME