image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test
  - Docker Image

# pylint:
#   stage: Static Analysis
#   allow_failure: true
#   script:
#   - pylint main.py

# unittests:
#   stage: Test
#   allow_failure: true
#   script:
#   - python test.py

Build Push:
  stage: Docker Image
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add python python-dev python pip
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_URL
    - echo "Hello There !!"
