image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test
  - Create Image

# pylint:
#   stage: Static Analysis
#   allow_failure: true
#   script:
#   - pylint main.py

# unittests:
#   stage: Test
#   allow_failure: true
#   script:
#   - python test.py

Build Push:
  stage: Create Image
  image: quay.io/buildah/stable:v1.21.0
  variables:
    STORAGE_DRIVER: "vfs"
    BUILDAH_FORMAT: "docker"
  before_script:
    - apk add --no-cache python3 py3-pip
  script:
    - buildah login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_URL
    # - docker build -t docker pull lbp.jfrog.io/default-docker-local/testapi .
    # - docker push docker pull lbp.jfrog.io/default-docker-local/testapi 
