image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test
  - Create Image

# pylint:
#   stage: Static Analysis
#   allow_failure: true
#   script:
#   - pylint main.py

# unittests:
#   stage: Test
#   allow_failure: true
#   script:
#   - python test.py

Build Push:
  stage: Create Image
  image: quay.io/buildah/stable:v1.18.0
  # before_script:
  #   - apk add --no-cache python3 py3-pip
  script:
    - buildah  bud --format=docker --storage-driver=vfs --no-cache -t lbp.jfrog.io/default-docker-local/testapi .
